name: Auto Assign PR

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      # Ref: https://github.com/marketplace/actions/auto-assign-action
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          # Ref: https://github.com/marketplace/actions/auto-assign-action#single-reviewers-list
          configuration-path: '.github/auto_assign.yml'
          # NOTE: `repo` scope personal access token (classic)
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
