# notify_reviewers_on_successful_checks がすぐに走らないようにするため5秒待つワークフローを用意する（応急処置）
name: Delayed Check for Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sample_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!