name: Tag Generation

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: 'Type of version to increment'
        required: true
        default: 'pre-release'
        options:
          - major
          - minor
          - patch
          - pre-release

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Fetch all tags
    - name: Fetch all tags
      run: git fetch --tags

    # Get the latest tag
    - name: Fetch latest tag
      id: latest-tag
      run: |
        echo "::set-output name=tag::$(git describe --tags --abbrev=0 || echo "0.0.0")"

    - name: Generate new tag
      id: generate-tag
      run: |
        LATEST_TAG=${{ steps.latest-tag.outputs.tag }}
        VERSION_TYPE=${{ github.event.inputs.versionType }}

        MAJOR=$(echo $LATEST_TAG | cut -d'.' -f1)
        MINOR=$(echo $LATEST_TAG | cut -d'.' -f2)
        PATCH=$(echo $LATEST_TAG | cut -d'.' -f3 | sed 's/-rc.*//')
        PRE_RELEASE=$(echo $LATEST_TAG | grep -oP 'rc\.\K\d+')

        case $VERSION_TYPE in
          major) 
            MAJOR=$((MAJOR+1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR+1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH+1))
            ;;
          pre-release)
            if [ -z "$PRE_RELEASE" ]; then
              PRE_RELEASE=1
            else
              PRE_RELEASE=$((PRE_RELEASE+1))
            fi
            ;;
        esac

        NEW_TAG="${MAJOR}.${MINOR}.${PATCH}"
        [ "$VERSION_TYPE" == "pre-release" ] && NEW_TAG="${NEW_TAG}-rc.${PRE_RELEASE}"

        echo "::set-output name=new-tag::$NEW_TAG"

    # Output the new tag
    - name: Output new tag
      run: |
        echo "Generated tag: ${{ steps.generate-tag.outputs.new-tag }}"

    # TODO: Slack notification
