name: Move PR Into Review Lane

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, ready_for_review, reopened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-project-automation
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: sample-project
          column: In Review
          # NOTE: `repo` scope personal access token (classic)
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
