name: Notify Reviewers on Assign

on:
  pull_request:
    types:
      - review_requested

jobs:
  notify_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get PR data
        id: pr_data
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          PR_DATA=$(gh pr view $PR_ID --json title,url,author,requestedReviewers)
          echo "::set-output name=pr_data::$PR_DATA"
          
      - name: Notify reviewers
        if: steps.pr_data.outputs.pr_data
        run: |
          PR_DATA="${{ steps.pr_data.outputs.pr_data }}"
          PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
          PR_URL=$(echo "$PR_DATA" | jq -r '.url')
          AUTHOR_NAME=$(echo "$PR_DATA" | jq -r '.author.login')
          REVIEWER_DATA=$(echo "$PR_DATA" | jq -r '.requestedReviewers.nodes[] | select(.reviews.nodes[]? | .state == "APPROVED" | not) | .login')

          # Load mapping
          GITHUB_TO_SLACK_MAPPING=$(cat .github/github_to_slack_mapping.json | jq .)
          AUTHOR_SLACK=$(echo $GITHUB_TO_SLACK_MAPPING | jq -r --arg AUTHOR "$AUTHOR_NAME" '.[$AUTHOR]')

          MENTIONS=""
          for reviewer in $REVIEWER_DATA; do
            slack_username=$(echo $GITHUB_TO_SLACK_MAPPING | jq -r --arg REVIEWER "$reviewer" '.[$REVIEWER]')
            MENTIONS="$MENTIONS@$slack_username "
          done

          if [ -n "$MENTIONS" ]; then
            SLACK_MESSAGE="{
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"$MENTIONS レビューをお願いします。\n\n$PR_TITLE\n$PR_URL\n\nby @$AUTHOR_SLACK\"
                  }
                }
              ]
            }"

            curl -s -X POST -H 'Content-type: application/json' --data "$SLACK_MESSAGE" "${{ secrets.SLACK_WEBHOOK_URL }}"
          fi
