name: Notify reviewers on successful checks

on:
  check_suite:
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.check_suite.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notify reviewers on Slack
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL_ID: "C05736775AM"
      run: |
        PR_ID=$(jq .pull_requests[0].number <(curl -s https://api.github.com/repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}))
        PR_DATA=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID)
        USERS=$(jq -r '.requested_reviewers | map(.login) | join(", ")' <<< $PR_DATA)
        REVIEWS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID/reviews)
        USERS_APPROVED=$(jq -r '[.[] | select(.state=="APPROVED") | .user.login] | unique | join(", ")' <<< $REVIEWS)

        PR_TITLE=$(jq -r '.title' <<< $PR_DATA)
        PR_SENDER=$(jq -r '.user.login' <<< $PR_DATA)
        PR_LINK=$(jq -r '.html_url' <<< $PR_DATA)

        MENTIONS=""
        for user in $USERS; do
          if [[ ! $USERS_APPROVED =~ (^|[[:space:]])$user($|[[:space:]]) ]]; then
            SLACK_USER_ID=$(curl -s -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" -H "Content-type: application/json; charset=utf-8" --data '{"username": "'$user'"}' https://slack.com/api/users.lookupByEmail | jq -r '.user.id')
            MENTIONS="$MENTIONS <@$SLACK_USER_ID>"
          fi
        done

        if [ -n "$MENTIONS" ]; then
          MESSAGE_TEXT="$MENTIONS レビューをお願いします。\nPR の CI が通りました。\n\n$PR_TITLE\n$PR_LINK\n\nby @$PR_SENDER"
        else
          MESSAGE_TEXT="PR の CI が通りました。\n\n$PR_TITLE\n$PR_LINK\n\nby @$PR_SENDER"
        fi

        curl -s -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" -H "Content-type: application/json; charset=utf-8" --data '{"channel": "'$SLACK_CHANNEL_ID'", "blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "'"$MESSAGE_TEXT"'"}}]}' https://slack.com/api/chat.postMessage
