name: Notify on successful checks

on:
  check_suite:
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.check_suite.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notify on Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_ID=$(jq .pull_requests[0].number <(curl -s https://api.github.com/repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}))
        PR_DATA=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID)

        PR_TITLE=$(jq -r '.title' <<< $PR_DATA)
        PR_SENDER=$(jq -r '.user.login' <<< $PR_DATA)
        PR_LINK=$(jq -r '.html_url' <<< $PR_DATA)

        APPROVED_USERS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID/reviews?per_page=100 | jq '[.[] | select(.state == "APPROVED") | .user.login] | unique')
        
        MENTIONS=""
        for reviewer in $(jq -r '.requested_reviewers.login' <<< $PR_DATA); do
          if [[ ! $APPROVED_USERS =~ $reviewer ]]; then
            MENTIONS+="@$reviewer "
          fi
        done

        if [ -z "$MENTIONS" ]; then
          MENTIONS_TEXT=""
        else
          MENTIONS_TEXT="\n$MENTIONSレビューをお願いします。"
        fi

        MESSAGE_TEXT="*PR の CI が通りました。*$MENTIONS_TEXT\n\nTitle: $PR_TITLE\nURL: $PR_LINK\n\nby @$PR_SENDER"

        curl -s -X POST -H "Content-type: application/json" --data '{"text": "'"${MESSAGE_TEXT}"'"}' $SLACK_WEBHOOK_URL
