name: Sample

on:
  workflow_dispatch:
    inputs:
      comment:
        required: true
        description: Sample

jobs:
  sample_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
