name: Set Milestone To PR

on:
  pull_request:
    types:
      - opened

jobs:
  set-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Set latest milestone to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Ref: PRにマイルストーンを自動設定 https://qiita.com/stnamco/items/06d2147c93a1cca97371
            // Ref: https://octokit.github.io/rest.js/v20
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'due_on',
              direction: 'desc',  // 最新のものから取得
              per_page: 1         // 最新のマイルストーンのみを取得
            });

            const latestMilestone = milestones.data[0];
            if (!latestMilestone) {
              console.log('No open milestones found');
              return;
            }

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              milestone: latestMilestone.number
            });
